### PR TITLE
update apostrophe version

### PR DESCRIPTION
**Pull request by triskuit**
## Summary
Update the apostrophe version in starter kits [PRO-4652](https://linear.app/apostrophecms/issue/PRO-4652/update-the-apostrophe-dependency-in-all-of-the-starter-kit-repo)

## What kind of change does this PR introduce?
- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [x] Other

## Make sure the PR fulfills these requirements:
- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

### CODE REVIEW

**Review by BoDonkey — CHANGES_REQUESTED** [review]
Please eliminate the package.json file from the repo and make sure that it has been added to the .gitignore file. Thanks!

**Comment by triskuit** [comment]
@BoDonkey I added the package-lock.json due to the following [build error](https://github.com/apostrophecms/starter-kit-ecommerce/actions/runs/5788286787/job/15686957552):
`npm ERR! 'npm ci' can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with 'npm install' before continuing.`
Not sure how to get around that without updating the package.json. Would you recomend updating `npm ci` to `npm install`?

**Comment by myovchev** [comment]
@BoDonkey Eliminating the `package-lock.json` will break the GitHub actions. 
@triskuit You can try and replace `npm ci` with `npm i` in the flow files. This would make the actions MUCH slower though.

**Comment by BoDonkey** [comment]
> @BoDonkey Eliminating the `package-lock.json` will break the GitHub actions. @triskuit You can try and replace `npm ci` with `npm i` in the flow files. This would make the actions MUCH slower though.

@myovchev which specific GitHub actions? Are they required and will they cause issues if someone clones this. One difficulty with leaving this in is that a few releases down the road and `npm ci` can end up resulting in out of date packages.

**Comment by myovchev** [comment]
@BoDonkey I haven't tested if action flows work with templates when the template is implemented in a new github repo. 
They are completely safe if every instance of `npm ci` is replaced with `npm i` in the `.github/workflows/*.yaml`.

**Comment by triskuit** [comment]
Removed `package-lock.json` and updated the test.yml file to get around github actions failing. Looks like they're passing now!

**Review by BoDonkey — APPROVED** [review]

**Pull request merged**
